import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3000),
  APP_ORIGIN: Joi.string().default('http://localhost:3000'),
  DATABASE_URL: Joi.string().required(),
  REDIS_URL: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().min(24).required(),
  JWT_ACCESS_TTL: Joi.string().default('15m'),
  REFRESH_TOKEN_TTL_DAYS: Joi.number().default(30),
  WEBSOCKET_TICKET_TTL_SECONDS: Joi.number().default(60),
  OTP_MODE: Joi.string().valid('mock', 'sayqal').default('mock'),
  OTP_MOCK_CODE: Joi.string().default('000000'),
  OTP_TTL_SECONDS: Joi.number().default(300),
  OTP_RESEND_COOLDOWN_SECONDS: Joi.number().default(120),
  OTP_MAX_ATTEMPTS: Joi.number().default(5),
  OTP_LOCKOUT_SECONDS: Joi.number().default(900),
  SMS_SAYQAL_URL: Joi.string().uri().optional(),
  SMS_SAYQAL_SECRET: Joi.string().optional(),
  SMS_SAYQAL_USERNAME: Joi.string().optional(),
  MAX_ACTIVE_DEVICES: Joi.number().default(3),
  SIGNED_PREKEY_ROTATION_DAYS: Joi.number().default(7),
  PUSH_PROVIDER: Joi.string().valid('logger', 'fcm').default('logger'),
  FCM_SERVICE_ACCOUNT_JSON: Joi.string().allow('').optional(),
  R2_ENDPOINT: Joi.string().required(),
  R2_ACCESS_KEY_ID: Joi.string().required(),
  R2_SECRET_ACCESS_KEY: Joi.string().required(),
  R2_BUCKET_NAME: Joi.string().default('birgap-backups'),
  R2_PRESIGNED_PUT_TTL_SECONDS: Joi.number().default(900),
  R2_PRESIGNED_GET_TTL_SECONDS: Joi.number().default(300),
  APNS_TEAM_ID: Joi.string().allow('').optional(),
  HMS_APP_ID: Joi.string().allow('').optional(),
  INTERNAL_API_KEY: Joi.string().min(32).required(),
  MESSAGE_EDIT_DELETE_LIMIT_HOURS: Joi.number().integer().min(1).default(48),
  ENABLE_MESSAGE_EDIT_DELETE_LIMIT: Joi.boolean().default(true),
  MEDIA_MAX_ATTACHMENTS_PER_MESSAGE: Joi.number().integer().min(1).default(10),
  MEDIA_PENDING_TIMEOUT_HOURS: Joi.number().integer().min(1).default(24),
  ADMIN_PHONE_HASHES: Joi.string().allow('').optional(),
  SUSPENSION_APPEAL_URL: Joi.string().uri().optional(),
  REPORTS_DAILY_LIMIT: Joi.number().integer().min(1).default(50),
  REPORTS_COLLUSION_THRESHOLD: Joi.number().integer().min(1).default(10),
  REPORTS_COLLUSION_WINDOW_HOURS: Joi.number().integer().min(1).default(1),
  REPORTS_PER_IP_PER_MINUTE: Joi.number().integer().min(1).default(10),
  TRUST_PROXY_HOPS: Joi.number().integer().min(0).max(5).default(0),
  REPORT_RETENTION_DAYS: Joi.number().integer().min(30).default(365),
  DAILY_METRICS_RETENTION_DAYS: Joi.number().integer().min(30).default(365),
});
